GET http://localhost:5000/api/admins?search=&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwOGE4ZmNiZWE2MWJlYzEyMjQ4MTQ4IiwiaWF0IjoxNjYxNTEyMDM2fQ.vFMuWGz5HFhTvnRyvv_F2dm6vJs9QXxkswXsgHYrXO0

### CREATE Admin
POST http://localhost:5000/api/admins/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwOGE4ZmNiZWE2MWJlYzEyMjQ4MTQ4IiwiaWF0IjoxNjYxNTEyMDM2fQ.vFMuWGz5HFhTvnRyvv_F2dm6vJs9QXxkswXsgHYrXO0

{
  "username": "admin",
  "password": "2018",
  "name":"Ha nguyen",
  "email": "hann@icetea.io",
  "isBoss": false
}

### UPDATE Admin
PUT http://localhost:5000/api/admins/update/63074a6678481ed583c99f28
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwNzRhMzc3ODQ4MWVkNTgzYzk5ZjI0IiwiaWF0IjoxNjYxNDI0MTU2fQ.Aon_agt16lAs1kJXB6bHmAsoGxK_GXUYd43NihIlNFY

{
  "username": "adminfake3",
  "password": "2018",
  "name":"Kien nguyen 2222",
  "email": "kienncpphasz@icetea.io",
  "isBoss": false
}

### ADMIN LOGIN
POST http://localhost:5000/api/admins/login
Content-Type: application/json

{
  "username": "admin",
  "password": "2018"
}

### GET List Job
GET http://localhost:5000/api/jobs

### GET Job Detail by Id
GET http://localhost:5000/api/jobs/2

### CREATE Job
POST http://localhost:5000/api/jobs/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwNmZhNjg3MWRiNzhhYzg3ZmJiMDBmIiwiaWF0IjoxNjYxNDAyNTc0fQ.3BLsaH3VGzSRuPwtzxhOIFh_4s9paPmyaCXEq49z7Ik

{
  "title": "React native dev 7",
  "category": "software-development",
  "level": "intern",
  "display": false,
  "location": "remote",
  "description": "<p>description development</p>",
  "requirements": "<p>requirements development</p>",
  "benefits": "<p>benefits development</p>"
}

###
PUT http://localhost:5000/api/jobs/update/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwNmZhNjg3MWRiNzhhYzg3ZmJiMDBmIiwiaWF0IjoxNjYxNDAyNTc0fQ.3BLsaH3VGzSRuPwtzxhOIFh_4s9paPmyaCXEq49z7Ik

{
  "title": "React native dev edited",
  "category": "software-development",
  "level": "intern",
  "display": false,
  "location": "ha-noi",
  "description": "<p>description development edited</p>",
  "requirements": "<p>requirements development edited</p>",
  "benefits": "<p>benefits development edited</p>"
}

### Delete Job
DELETE  http://localhost:5000/api/jobs/delete/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwNmZhNjg3MWRiNzhhYzg3ZmJiMDBmIiwiaWF0IjoxNjYxNDAyNTc0fQ.3BLsaH3VGzSRuPwtzxhOIFh_4s9paPmyaCXEq49z7Ik

### Delete Admin
DELETE  http://localhost:5000/api/admins/delete/6306fa6871db78ac87fbb00f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwOGE4ZmNiZWE2MWJlYzEyMjQ4MTQ4IiwiaWF0IjoxNjYxNTEyMDM2fQ.vFMuWGz5HFhTvnRyvv_F2dm6vJs9QXxkswXsgHYrXO0

### Get list jobs
GET  http://localhost:5000/api/jobs?page=2&search=&display=&level=intern
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMwNmZhNjg3MWRiNzhhYzg3ZmJiMDBmIiwiaWF0IjoxNjYxNDAyNTc0fQ.3BLsaH3VGzSRuPwtzxhOIFh_4s9paPmyaCXEq49z7Ik
